fastq_base: ../../data/fastqs/
reference_base: ../../reference/
# {name}/genes.gtf
# {name}/genome.fa
# {name}/transcriptome.fa
# {name}/kallisto.idx
datasets:
  - name: arabidopsis-SRR8257100_v2
    ref_name: arabidopsis-tair10
    r1: 
      - SRR8257100_S1_L001_R2_001.fastq.gz
    r2: 
      - SRR8257100_S1_L001_R2_001.fastq.gz
      
  - name: fly-SRR8513910_v2
    ref_name: fly-dm6
    r1: 
      - SRR8513910_S1_L001_R1_001.fastq.gz
    r2:
      - SRR8513910_S1_L001_R2_001.fastq.gz
      
  - name: human_mouse-hgmm1k_v2
    ref_name: human_mouse-hg19_mm10
    r1:
      - hgmm_1k_v2_S1_L001_R1_001.fastq.gz
      - hgmm_1k_v2_S1_L002_R1_001.fastq.gz
    r2: 
      - hgmm_1k_v2_S1_L001_R2_001.fastq.gz
      - hgmm_1k_v2_S1_L002_R2_001.fastq.gz

  - name: human-SRR8327928_v2
    ref_name: human-grch38
    r1:
      - bamtofastq_S1_L001_R1_001.fastq.gz
      - bamtofastq_S1_L002_R1_001.fastq.gz
      - bamtofastq_S1_L003_R1_001.fastq.gz
      - bamtofastq_S1_L004_R1_001.fastq.gz
    r2:
      - bamtofastq_S1_L001_R2_001.fastq.gz
      - bamtofastq_S1_L002_R2_001.fastq.gz
      - bamtofastq_S1_L003_R2_001.fastq.gz
      - bamtofastq_S1_L004_R2_001.fastq.gz
    
  - name: human-SRR8524760_v2
    ref_name: human-grch38
    r1:
      - bamtofastq_S1_L001_R1_001.fastq.gz
      - bamtofastq_S1_L002_R1_001.fastq.gz
      - bamtofastq_S1_L003_R1_001.fastq.gz
      - bamtofastq_S1_L004_R1_001.fastq.gz
    r2:
      - bamtofastq_S1_L001_R2_001.fastq.gz
      - bamtofastq_S1_L002_R2_001.fastq.gz
      - bamtofastq_S1_L003_R2_001.fastq.gz
      - bamtofastq_S1_L004_R2_001.fastq.gz
      
  - name: mouse-EMTAB7320_v2
    ref_name: mouse-mm10
    r1:
      - SAG657A3_S2_L002_R1_001.fastq.gz
    r2:
      - SAG657A3_S2_L002_R2_001.fastq.gz
      
  - name: mouse-heart1k_v2
    ref_name: mouse-mm10
    r1:
      - heart_1k_v2_S1_L001_R1_001.fastq.gz
      - heart_1k_v2_S1_L002_R1_001.fastq.gz
    r2:
      - heart_1k_v2_S1_L001_R2_001.fastq.gz
      - heart_1k_v2_S1_L002_R2_001.fastq.gz
    
  - name: mouse-SRR6998058_v2
    ref_name: mouse-mm10
    r1:
      - bamtofastq_S1_L001_R1_001.fastq.gz
      - bamtofastq_S1_L002_R1_001.fastq.gz
      - bamtofastq_S1_L003_R1_001.fastq.gz
      - bamtofastq_S1_L004_R1_001.fastq.gz
    r2:
      - bamtofastq_S1_L001_R2_001.fastq.gz
      - bamtofastq_S1_L002_R2_001.fastq.gz
      - bamtofastq_S1_L003_R2_001.fastq.gz
      - bamtofastq_S1_L004_R2_001.fastq.gz
      
  - name: mouse-SRR8206317_v2
    ref_name: mouse-mm10
    r1:
      - bamtofastq_S1_L001_R1_001.fastq.gz
      - bamtofastq_S1_L002_R1_001.fastq.gz
      - bamtofastq_S1_L003_R1_001.fastq.gz
      - bamtofastq_S1_L004_R1_001.fastq.gz
    r2:
      - bamtofastq_S1_L001_R2_001.fastq.gz
      - bamtofastq_S1_L002_R2_001.fastq.gz
      - bamtofastq_S1_L003_R2_001.fastq.gz
      - bamtofastq_S1_L004_R2_001.fastq.gz
    
  - name: mouse-SRR8599150_v2
    ref_name: mouse-mm10
    r1:
      - SRR8599150_S1_L001_R1_001.fastq.gz
    r2:
      - SRR8599150_S1_L001_R2_001.fastq.gz
    
  - name: mouse-SRR8639063_v2
    ref_name: mouse-mm10
    r1:
      - SRR8639063_S1_L001_R1_001.fastq.gz
    r2:
      - SRR8639063_S1_L001_R2_001.fastq.gz
    
  - name: rat-SRR7299563_v2
    ref_name: rat_rnor6
    r1:
      - bamtofastq_S1_L001_R1_001.fastq.gz
      - bamtofastq_S1_L001_R1_002.fastq.gz
      - bamtofastq_S1_L002_R1_001.fastq.gz
      - bamtofastq_S1_L002_R1_002.fastq.gz
    r2:
      - bamtofastq_S1_L001_R2_001.fastq.gz
      - bamtofastq_S1_L001_R2_002.fastq.gz
      - bamtofastq_S1_L002_R2_001.fastq.gz
      - bamtofastq_S1_L002_R2_002.fastq.gz
      
    
  - name: worm-SRR8611943_v2
    ref_name: worm-ws260
    r1:
      - SRR8611943_S1_L001_R1_001.fastq.gz
    r2:
      - SRR8611943_S1_L001_R2_001.fastq.gz
    
  - name: zebrafish-SRR6956073_v2
    ref_name: zebrafish-dr82
    r1:
      - bamtofastq_S1_L001_R1_001.fastq.gz
      - bamtofastq_S1_L002_R1_001.fastq.gz
      - bamtofastq_S1_L003_R1_001.fastq.gz
      - bamtofastq_S1_L004_R1_001.fastq.gz
      - bamtofastq_S1_L005_R1_001.fastq.gz
      - bamtofastq_S1_L006_R1_001.fastq.gz
      - bamtofastq_S1_L007_R1_001.fastq.gz
    r2:
      - bamtofastq_S1_L001_R2_001.fastq.gz
      - bamtofastq_S1_L002_R2_001.fastq.gz
      - bamtofastq_S1_L003_R2_001.fastq.gz
      - bamtofastq_S1_L004_R2_001.fastq.gz
      - bamtofastq_S1_L005_R2_001.fastq.gz
      - bamtofastq_S1_L006_R2_001.fastq.gz
      - bamtofastq_S1_L007_R2_001.fastq.gz
