datasets:
  - name: human_mouse-hgmm10k_v3
    reference_path: ../../reference/human_mouse-hg19_mm10/
  - name: human_mouse-hgmm1k_v3
    reference_path: ../../reference/human_mouse-hg10_mm10/
  - name: human-pbmc10k_v3
    reference_path: ../../reference/human-grch38/
  - name: human-pbmc1k_v3
    reference_path: ../../reference/human-grch38/
  - name: mouse-heart1k_v3
    reference_path: ../../reference/mouse-mm10/
  - name: mouse-neuron10k_v3
    reference_path: ../../reference/mouse-mm10/
